### ISSUE TITLE
Multiple LP fields - only first one works

### ISSUE THREAD

**Issue by gordonadams** [ahebrank/ACF-Link-Picker-Field#26]
Hello
Just noticed this behaviour.  Not sure if this is happening since update to ACF or ACF:LP. 
Have  multiple link picker fields but when the edit/remove/insert links are used on any bar the first one the edit page just refreshes.
Console shows javascript error but not sure if related...
**/wp-content/plugins/acf-link-picker-field/js/input.js
input.js:118 Uncaught TypeError: Cannot read property 'replace' of undefined(…)**
>>>
if (!post_id || post_id == 0) {
                get_postid(url, $postid_input.attr('id').replace('-postid', ''));
            }

Also there's is a warning that displays briefly on console before page refresh

**Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the user's experience**

Advanced Custom Fields: Version 4.4.11
Advanced Custom Fields: Link Picker Version 1.2.7 

I disabled all plugins bar ACF and makes no difference.

Regards,
Gordon

**Comment by gordonadams** [comment]
Have tested on a new site with ACF and ACF:LP.

It seems to happen when you edit a post that contains existing links. In this case you can only edit/remove the first link (or insert any empty ones before it) before you have to save. 

For example, to edit the fourth link, you would have to remove the first link and update, then remove the second link (which is now the first link with a value) and save, then remove the third link and save. Now you can do whatever needs to be done to the fourth link (as it is now the first link with a value). Afterwards you should be able to reinsert the first three links into the empty links above in one go (with only one final save) as the ones prior to the one with the first value seem to work ok.

**Comment by ahebrank** [comment]
I'm guessing this has to do with incompatibility with ACF 4 -- I've added some checks to try to prevent JS errors when post ID fields aren't present (they're only in the ACF 5 version).  Before I push this update to WP, can you test the master branch and see if suppressing JS errors fixes your problems? (I don't have an ACF 4 site to test with)

**Comment by gordonadams** [comment]
Perfect.

Works a charm.

Well done.
ᐧ

**Comment by ahebrank** [comment]
OK, thanks for testing, I'll push it to WP plugins shortly -- update should be available from there soon.
