### ISSUE TITLE
This doesn't work in a repeating field

### ISSUE THREAD

**Issue by emregan** [ahebrank/ACF-Link-Picker-Field#27]

**Comment by dmarkowicz** [comment]
Which version of ACF? 4 or 5?

**Comment by ahebrank** [comment]
We're gonna need a lot more details to be able to confirm the bug and try to replicate it.  What version of WP? ACF? The link picker? The browser? Any javascript errors? When you say "doesn't work", does it not show up?  Not record data?  Both?  Something else?

Make sure also you're using *this* plugin, not the obsolete version with the same name: https://wordpress.org/plugins/acf-link-picker-field/ (only one has compatibility with current WP).

**Comment by ahebrank** [comment]
Please reopen if you have more information.
