### ISSUE TITLE
return id?

### ISSUE THREAD

**Issue by nicmare** [ahebrank/ACF-Link-Picker-Field#8]
would be nice if the returned object also contain the id of the target (if it is a post type). then i can do a lot more with it. thank you!

**Comment by ahebrank** [comment]
I'm not sure the post ID is available from the underlying picker widget (we're just very lightly wrapping this existing widget), but I'll take a look.

**Comment by ahebrank** [comment]
v 1.2.1 attempts to add a post ID to the field data.  It's not available in the underlying wp_link, so I'd consider this an experimental feature.  IDs won't be added to existing field values; they'll each need to be updated by opening and submitting the link modal.
